import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import style from "../styles/style.module.css";
import form from "../styles/Form.module.css";
import register from "../public/register.png";
import signin from "../public/signin.png";
import Link from "next/link";
//import { signIn, signOut } from 'next-auth/client/_utils';
import { signIn, signOut, useSession } from "next-auth/react";
import axios from "axios";
import React from 'react';

//const { data: session, status: Loading } = useSession();
  //console.log(session, Loading);
export default class extends React.Component {
  constructor (props)
  {
    super(props);
    this.handleChangeFirstname = this.handleChangeFirstname.bind(this);
    this.handleChangeLastname = this.handleChangeLastname.bind(this);
    this.handleChangeEmail = this.handleChangeEmail.bind(this);
    this.handleChangePassword = this.handleChangePassword.bind(this);
    this.handleChangeRPassword = this.handleChangeRPassword.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
    this.state = {
      firstname: '',
      lastname: '',
      email: '',
      password: '',
      rpassword:''
    };
  }

  
  handleChangeFirstname(e) 
    {
      this.setState({
        firstname: e.target.value
      })
  };
  handleChangeLastname (e) 
  {
    this.setState({
      lastname: e.target.value
    })
};
 handleChangeEmail (e) 
 {
   this.setState({
     email: e.target.value
   })
};
  handleChangePassword (e) 
  {
    this.setState({
      password: e.target.value
    })
}
handleChangeRPassword (e) 
{
  
  this.setState({rpassword: e.target.value})

}
openNotificationWithIcon = type => {
  notification[type]({
    message: "sign up successfully"
  });
};
 handleSubmit (e) {
    e.preventDefault();
    if(this.state.password !== this.state.rpassword){
   console.log("The passwords doesn't match")}
    const user =
    {
      firstname: this.state.firstname,
      lastname: this.state.lastname,
      email: this.state.email,
      password: this.state.password
    }
    console.log(user);
    try {
   axios.post(
        "http://localhost:3000/api/register",user) 
        .then(res => console.log(res.data));
         window.location.replace('/signin')
       
    } catch (error) {

      console.log("error " + error);
    }
  };
  render(){
  return (
  <div> <div className={styles.container}>
    <Head>
      <title>My App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <div className={styles.signin}>
        <li className={styles.inline}>
          <Link href="signin">
            <a>Sign in</a>
          </Link>
        </li>
        <li className={styles.inline}>
          <Link href="/register">
            <a>Register</a>
          </Link>
        </li>
      </div>
      <navigator>
        <span style={{ backgroundColor: "#333" }}>
          <a href="#home" className={styles.logo}>
            <div className={styles.left}></div>
            <div className={styles.right}></div>
          </a>
        </span>
        <ul className={styles.ul}>
          <li className={styles.li}>
            <a href="#home">Home</a>
          </li>
          <li className={styles.li}>
            <a href="#aboutus">About us</a>
          </li>
          <li className={styles.li}>
            <a href="#contact">Contact us</a>
          </li>
          <li className={styles.li} style={{ float: "right" }}>
            <div className={styles.dot} href="#about">
              Ar
            </div>
          </li>
        </ul>
      </navigator>
    </Head>

    <main className={styles.main}>
      <div className={form.box}>
        <div className={form.Sbox}>
          <div className={form.Rbox}>
            <Image className={form.register} src={register} alt="register" />
            <h4> Register </h4>
            <p className={form.p}> Browse and find what you need</p>
          </div>
          <div className={form.lv}></div>
          <div className={form.Lbox}>
            <Image className={form.signin} src={signin} alt="signin" />
            <h4> Sign in </h4>
            <p className={form.p}>
              Already have an account then welcome back.
            </p>
          </div>
        </div>
      </div>
      <form className={form.form}
       onSubmit={this.handleSubmit}>
        <div className={form.inputnames}>
          <input
            className={form.inputname}
            value={this.state.firstname}
            onChange={this.handleChangeFirstname}
            type="text"
           name="firstname"
           placeholder="FirstName*"
            
          />
          <input
            className={form.inputname}
            type="text"
            placeholder="LastName*"
            value={this.state.lastname}
            onChange={this.handleChangeLastname}
          />
        </div>
        <input
          className={form.input}
          value={this.state.email}
          type="text"
          placeholder="Email*"
          onChange={this.handleChangeEmail}
        />
        <input
          className={form.input}
          type="password"
          placeholder="Password*"
          value={this.state.password}
          onChange={this.handleChangePassword}
        />
        <input
          className={form.input}
          type="password"
          placeholder="Repeat Password*"
          value={this.state.rpassword}
          onChange={this.handleChangeRPassword}
        />
        <input className={form.submit} type="submit" value={"Submit"} />
      </form>
    </main>

    <footer className={styles.footer}>
      <span className="{styles.containere}">
        <div className={style.left} style={{ marginTop: "10px" }}></div>
        <div className={style.right} style={{ marginTop: "40px" }}></div>
      </span>
      <p> © All Rights Reserved</p>
    </footer>
  </div>
</div>)


}
}
